In [1]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv('data.csv')
df.head(5)

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [4]:
df.tail(5)

          Date Category  Value   Product  Sales Region
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [5]:
df.describe()

           Value       Sales
count  47.000000   46.000000
mean   51.744681  557.130435
std    29.050532  274.598584
min     2.000000  108.000000
25%    27.500000  339.000000
50%    54.000000  591.500000
75%    70.000000  767.500000
max    99.000000  992.000000

In [6]:
df.dtypes

Date         object
Category     object
Value       float64
Product      object
Sales       float64
Region       object
dtype: object

In [10]:
df.isnull().any(axis=1)

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11     True
12    False
13    False
14    False
15     True
16    False
17     True
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28     True
29    False
30    False
31    False
32    False
33     True
34    False
35     True
36    False
37     True
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
dtype: bool

In [11]:
df[df.isnull().any(axis=1)]

          Date Category  Value   Product  Sales Region
11  2023-01-12        B   60.0  Product2    NaN   West
15  2023-01-16        C    NaN  Product1  895.0  North
17  2023-01-18        C    NaN  Product1  108.0   West
28  2023-01-29        B    NaN  Product3  617.0  North
33  2023-02-03        C   27.0  Product3    NaN   East
35  2023-02-05        B   60.0  Product2    NaN   West
37  2023-02-07        C    2.0  Product1    NaN  North

In [12]:
df.isnull().sum()

Date        0
Category    0
Value       3
Product     0
Sales       4
Region      0
dtype: int64

In [15]:
df_filled=df.fillna(0)

In [17]:
df['Sales_fill']=df['Sales'].fillna(df['Sales'].mean())

In [21]:
df[df.isnull().any(axis=1)]

          Date Category  Value   Product  Sales Region  Sales_fill
11  2023-01-12        B   60.0  Product2    NaN   West  557.130435
15  2023-01-16        C    NaN  Product1  895.0  North  895.000000
17  2023-01-18        C    NaN  Product1  108.0   West  108.000000
28  2023-01-29        B    NaN  Product3  617.0  North  617.000000
33  2023-02-03        C   27.0  Product3    NaN   East  557.130435
35  2023-02-05        B   60.0  Product2    NaN   West  557.130435
37  2023-02-07        C    2.0  Product1    NaN  North  557.130435

In [22]:
df=df.rename(columns={'Date':'Sales Date'})
df.head(5)

   Sales Date Category  Value   Product  Sales Region  Sales_fill
0  2023-01-01        A   28.0  Product1  754.0   East       754.0
1  2023-01-02        B   39.0  Product3  110.0  North       110.0
2  2023-01-03        C   32.0  Product2  398.0   East       398.0
3  2023-01-04        B    8.0  Product1  522.0   East       522.0
4  2023-01-05        B   26.0  Product3  869.0  North       869.0

In [24]:
df['Value_new']=df['Value'].fillna(df['Value'].mean()).astype(int)
df.head()

   Sales Date Category  Value   Product  Sales Region  Sales_fill  Value_new
0  2023-01-01        A   28.0  Product1  754.0   East       754.0         28
1  2023-01-02        B   39.0  Product3  110.0  North       110.0         39
2  2023-01-03        C   32.0  Product2  398.0   East       398.0         32
3  2023-01-04        B    8.0  Product1  522.0   East       522.0          8
4  2023-01-05        B   26.0  Product3  869.0  North       869.0         26

In [25]:
df['New Value']=df['Value'].apply(lambda x:x*2)
df.head()

,Sales Date,Category,Value,Product,Sales,Region,Sales_fill,Value_new,New Value
0,2023-01-01,A,28.0,Product1,754.0,East,754.0,28,56.0
1,2023-01-02,B,39.0,Product3,110.0,North,110.0,39,78.0
2,2023-01-03,C,32.0,Product2,398.0,East,398.0,32,64.0
3,2023-01-04,B,8.0,Product1,522.0,East,522.0,8,16.0
4,2023-01-05,B,26.0,Product3,869.0,North,869.0,26,52.0

In [26]:
group_mean=df.groupby('Product')['Value'].mean()
group_mean

Product
Product1    46.214286
Product2    52.800000
Product3    55.166667
Name: Value, dtype: float64

In [ ]:
group_sum=df.groupby(['Product','Region'])['Value'].sum()
group_sum

Product   Region
Product1  East      292.0
          North       9.0
          South     100.0
          West      246.0
Product2  East       56.0
          North     127.0
          South     181.0
          West      428.0
Product3  East      202.0
          North     203.0
          South     215.0
          West      373.0
Name: Value, dtype: float64

In [ ]:
group_sum=df.groupby(['Product','Region','Category'])['Value'].sum()
group_sum

Product   Region  Category
Product1  East    A           172.0
                  B            23.0
                  C            97.0
          North   B             7.0
                  C             2.0
          South   B             6.0
                  C            94.0
          West    A            62.0
                  C           184.0
Product2  East    A            24.0
                  C            32.0
          North   C           127.0
          South   C           181.0
          West    A           117.0
                  B           219.0
                  C            92.0
Product3  East    A           139.0
                  C            63.0
          North   B           127.0
                  C            76.0
          South   A            70.0
                  B            63.0
                  C            82.0
          West    A            93.0
                  B           173.0
                  C           107.0
Name: Value, dtype: float64

In [37]:
group_sum=df.groupby(['Product','Region'])['Value'].mean()
group_sum

Product   Region
Product1  East      41.714286
          North      4.500000
          South     50.000000
          West      82.000000
Product2  East      28.000000
          North     63.500000
          South     60.333333
          West      53.500000
Product3  East      50.500000
          North     40.600000
          South     71.666667
          West      62.166667
Name: Value, dtype: float64

In [40]:
group_agg=df.groupby('Region')['Value'].agg(['mean','sum','count','min','max'])
group_agg

             mean     sum  count   min   max
Region
East    42.307692   550.0     13   8.0  97.0
North   37.666667   339.0      9   2.0  71.0
South   62.000000   496.0      8   6.0  94.0
West    61.588235  1047.0     17  17.0  99.0