In [1]:
import pandas as pd
import numpy as np

In [5]:
df=pd.read_csv('sales1_data.csv')
df.head()

         Date   Product  Sales Region
0  2023-01-01  Product3  738.0   West
1  2023-01-02  Product2  868.0  North
2  2023-01-03  Product2  554.0   West
3  2023-01-04  Product1  618.0  South
4  2023-01-05  Product3  501.0   East

In [6]:
df.describe()

            Sales
count   19.000000
mean   554.000000
std    231.543372
min    124.000000
25%    381.500000
50%    554.000000
75%    737.500000
max    868.000000

In [7]:
df.dtypes

Date        object
Product     object
Sales      float64
Region      object
dtype: object

In [8]:
df.tail()

          Date   Product  Sales Region
20  2023-01-21  Product2    NaN   West
21  2023-01-22  Product3  296.0   West
22  2023-01-23  Product2  737.0   West
23  2023-01-24  Product3  531.0   East
24  2023-01-25  Product2  834.0  North

In [11]:
df.isnull().any(axis=1)

0     False
1     False
2     False
3     False
4     False
5      True
6     False
7     False
8     False
9     False
10    False
11     True
12     True
13    False
14    False
15    False
16     True
17     True
18    False
19    False
20     True
21    False
22    False
23    False
24    False
dtype: bool

In [12]:
df[df.isnull().any(axis=1)]

          Date   Product  Sales Region
5   2023-01-06  Product1    NaN   West
11  2023-01-12  Product3    NaN   East
12  2023-01-13  Product3    NaN   East
16  2023-01-17  Product1    NaN  South
17  2023-01-18  Product1    NaN  South
20  2023-01-21  Product2    NaN   West

In [13]:
df.isnull().sum()

Date       0
Product    0
Sales      6
Region     0
dtype: int64

In [14]:
df['Sales_fill']=df['Sales'].fillna(df['Sales'].mean())

In [15]:
df[df.isnull().any(axis=1)]

          Date   Product  Sales Region  Sales_fill
5   2023-01-06  Product1    NaN   West       554.0
11  2023-01-12  Product3    NaN   East       554.0
12  2023-01-13  Product3    NaN   East       554.0
16  2023-01-17  Product1    NaN  South       554.0
17  2023-01-18  Product1    NaN  South       554.0
20  2023-01-21  Product2    NaN   West       554.0

In [16]:
df=df.rename(columns={'Date':'Sales Date'})

In [17]:
df.head()

   Sales Date   Product  Sales Region  Sales_fill
0  2023-01-01  Product3  738.0   West       738.0
1  2023-01-02  Product2  868.0  North       868.0
2  2023-01-03  Product2  554.0   West       554.0
3  2023-01-04  Product1  618.0  South       618.0
4  2023-01-05  Product3  501.0   East       501.0

In [18]:
df['Sales_new']=df['Sales_fill'].astype(int)
df.head()

   Sales Date   Product  Sales Region  Sales_fill  Sales_new
0  2023-01-01  Product3  738.0   West       738.0        738
1  2023-01-02  Product2  868.0  North       868.0        868
2  2023-01-03  Product2  554.0   West       554.0        554
3  2023-01-04  Product1  618.0  South       618.0        618
4  2023-01-05  Product3  501.0   East       501.0        501

In [20]:
df['New Sales']=df['Sales'].apply(lambda x:x*10)
df.head()

   Sales Date   Product  Sales Region  Sales_fill  Sales_new  New Sales
0  2023-01-01  Product3  738.0   West       738.0        738     7380.0
1  2023-01-02  Product2  868.0  North       868.0        868     8680.0
2  2023-01-03  Product2  554.0   West       554.0        554     5540.0
3  2023-01-04  Product1  618.0  South       618.0        618     6180.0
4  2023-01-05  Product3  501.0   East       501.0        501     5010.0

In [24]:
group_mean=df.groupby(['Product','Region'])['Sales'].mean()
group_mean

Product   Region
Product1  South     408.333333
          West             NaN
Product2  North     658.000000
          South     816.000000
          West      645.500000
Product3  East      569.333333
          South     309.500000
          West      558.750000
Name: Sales, dtype: float64

In [25]:
group_sum=df.groupby(['Product','Region'])['Sales'].sum()
group_sum

Product   Region
Product1  South     1225.0
          West         0.0
Product2  North     2632.0
          South      816.0
          West      1291.0
Product3  East      1708.0
          South      619.0
          West      2235.0
Name: Sales, dtype: float64

In [29]:
group_agg=df.groupby(['Product','Region'])['Sales'].agg(['mean','sum','count','min','max'])
group_agg

                       mean     sum  count    min    max
Product  Region
Product1 South   408.333333  1225.0      3  183.0  618.0
         West           NaN     0.0      0    NaN    NaN
Product2 North   658.000000  2632.0      4  124.0  868.0
         South   816.000000   816.0      1  816.0  816.0
         West    645.500000  1291.0      2  554.0  737.0
Product3 East    569.333333  1708.0      3  501.0  676.0
         South   309.500000   619.0      2  280.0  339.0
         West    558.750000  2235.0      4  296.0  738.0

In [30]:
group_agg=df.groupby(['Product','Region'])['Sales_fill'].agg(['mean','sum','count','min','max'])
group_agg

                   mean     sum  count    min    max
Product  Region
Product1 South   466.60  2333.0      5  183.0  618.0
         West    554.00   554.0      1  554.0  554.0
Product2 North   658.00  2632.0      4  124.0  868.0
         South   816.00   816.0      1  816.0  816.0
         West    615.00  1845.0      3  554.0  737.0
Product3 East    563.20  2816.0      5  501.0  676.0
         South   309.50   619.0      2  280.0  339.0
         West    558.75  2235.0      4  296.0  738.0