### Nominal/OHE Encoding

In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [2]:
df=pd.DataFrame({
    'color':['red','blue','green','green','red','blue']
})

In [3]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [4]:
encoder=OneHotEncoder()

In [5]:
encoded=encoder.fit_transform(df[['color']]).toarray()

In [6]:
encoder_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [7]:
encoder_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [8]:
encoder.transform([['blue']]).toarray()

e:\ML Bootcamp Krish Naik\Code\venv\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

In [9]:
pd.concat([df,encoder_df],axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5   blue         1.0          0.0        0.0

#### Assignment

In [11]:
import seaborn as sns
df=sns.load_dataset('tips')

In [12]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [15]:
encoded=encoder.fit_transform(df[['sex']]).toarray()

In [16]:
encoder_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [18]:
encoder_df.head()

   sex_Female  sex_Male
0         1.0       0.0
1         0.0       1.0
2         0.0       1.0
3         0.0       1.0
4         1.0       0.0

In [20]:
df['sex'].head()

0    Female
1      Male
2      Male
3      Male
4    Female
Name: sex, dtype: category
Categories (2, object): ['Male', 'Female']

In [23]:
encoder.transform([['Female']]).toarray()

e:\ML Bootcamp Krish Naik\Code\venv\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0.]])

In [26]:
pd.concat([df['sex'],encoder_df],axis=1)

        sex  sex_Female  sex_Male
0    Female         1.0       0.0
1      Male         0.0       1.0
2      Male         0.0       1.0
3      Male         0.0       1.0
4    Female         1.0       0.0
..      ...         ...       ...
239    Male         0.0       1.0
240  Female         1.0       0.0
241    Male         0.0       1.0
242    Male         0.0       1.0
243  Female         1.0       0.0

[244 rows x 3 columns]

## Label Encoding

In [10]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [11]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder=LabelEncoder()

In [13]:
lbl_encoder.fit_transform(df[['color']])

e:\ML Bootcamp Krish Naik\Code\venv\lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 1, 2, 0])

In [16]:
lbl_encoder.transform([['red']])

e:\ML Bootcamp Krish Naik\Code\venv\lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([2])

## Ordinal Encoding

In [17]:
from sklearn.preprocessing import OrdinalEncoder

In [18]:
df=pd.DataFrame({
    'size':['small','medium','large','medium','small','large']
})

In [19]:
df

     size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [20]:
encoder=OrdinalEncoder(categories=[['small','medium','large']])

In [21]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [24]:
encoder.transform([['large']])

e:\ML Bootcamp Krish Naik\Code\venv\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[2.]])

## Target Guided Ordinal Encoding

In [1]:
import pandas as pd
df=pd.DataFrame({
    'city':['New York','London','Paris','Tokyo','New York','Paris'],
    'price':[200,150,300,250,180,320]
})

In [2]:
df

       city  price
0  New York    200
1    London    150
2     Paris    300
3     Tokyo    250
4  New York    180
5     Paris    320

In [3]:
mean_price=df.groupby('city')['price'].mean().to_dict()

In [4]:
df['city_encoded']=df['city'].map(mean_price)

In [5]:
df

       city  price  city_encoded
0  New York    200         190.0
1    London    150         150.0
2     Paris    300         310.0
3     Tokyo    250         250.0
4  New York    180         190.0
5     Paris    320         310.0

In [6]:
df[['price','city_encoded']]

   price  city_encoded
0    200         190.0
1    150         150.0
2    300         310.0
3    250         250.0
4    180         190.0
5    320         310.0

### Assignment

In [9]:
import seaborn as sns
df=sns.load_dataset('tips')

In [10]:
df[['total_bill','time']]

     total_bill    time
0         16.99  Dinner
1         10.34  Dinner
2         21.01  Dinner
3         23.68  Dinner
4         24.59  Dinner
..          ...     ...
239       29.03  Dinner
240       27.18  Dinner
241       22.67  Dinner
242       17.82  Dinner
243       18.78  Dinner

[244 rows x 2 columns]

In [13]:
mean_bill=df.groupby('time')['total_bill'].mean().to_dict()

C:\Users\Kanishk\AppData\Local\Temp\ipykernel_1388\3401611641.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  mean_bill=df.groupby('time')['total_bill'].mean().to_dict()

In [14]:
mean_bill

{'Lunch': 17.168676470588235, 'Dinner': 20.79715909090909}

In [15]:
df['time_encoded']=df['time'].map(mean_bill)

In [ ]:
df[['time_encoded','time','total_bill']]

    time_encoded    time  total_bill
0      20.797159  Dinner       16.99
1      20.797159  Dinner       10.34
2      20.797159  Dinner       21.01
3      20.797159  Dinner       23.68
4      20.797159  Dinner       24.59
..           ...     ...         ...
239    20.797159  Dinner       29.03
240    20.797159  Dinner       27.18
241    20.797159  Dinner       22.67
242    20.797159  Dinner       17.82
243    20.797159  Dinner       18.78

[244 rows x 3 columns]